#!/usr/bin/env ruby
# coding: utf-8

require "jupyter_to_scrapbox"
require 'thor'

module JupyterToScrapbox
  class CLI < Thor
    class_option :help, type: :boolean, aliases: '-h', desc: 'help message.'
    class_option :version, type: :boolean, desc: 'version'
    default_task :help

    method_option :verbose, type: :boolean, aliases: '-v', desc: 'verbose message'
    method_option :moderate, type: :boolean, aliases: '-m', desc: 'moderate mode: do not convert markdown notations'
    desc 'converts FILES [options]', 'Convert jupyter-notebook files to scrapbox-json'

    def convert(*paths)
      JupyterToScrapbox::Converter.set_verbose() if options[:verbose]
      JupyterToScrapbox::Converter.set_moderate() if options[:moderate]
      paths.each do |path|
        JupyterToScrapbox::Converter.add(path)
      end
      JupyterToScrapbox::Converter.start()
      # puts "Hello "+path
    end
    desc 'version', 'version'
    def version
      p JupyterToScrapbox::VERSION
    end
  end
end

JupyterToScrapbox::CLI.start(ARGV)
